REPO_ROOT ?= ../../..
SPEC := recovery.lf
BIN = $(DIST_DIR)/parser-recovery-cpp-demo
INPUT ?= input.recovery
LOG ?= $(DIST_DIR)/parser-recovery-cpp-demo.log
RUN_ARGS = $(INPUT) --log $(LOG) --assert
TEST_ARGS = $(INPUT) --log $(LOG) --assert

include ../../mk/cpp.mk
