REPO_ROOT ?= ../../..
SPEC := recovery.lf
PROJECT := ParserRecoveryCSharp.csproj
INPUT ?= input.recovery
RUN_ARGS = --input $(INPUT) --assert
TEST_ARGS = --input $(INPUT) --assert

include ../../mk/csharp.mk
