REPO_ROOT ?= ../../..
SPEC := vehicle.lf
BIN = $(DIST_DIR)/vehicle-report-cpp-demo
INPUT ?= ../../testdata/vehicle-report/valid/basic.vehicle
LOG ?= $(DIST_DIR)/vehicle-report-cpp-demo.log

include ../../mk/cpp.mk
