REPO_ROOT ?= ../../..
SPEC := vehicle.lf
BIN = $(DIST_DIR)/vehicle-report-c-demo
INPUT ?= ../../testdata/vehicle-report/valid/basic.vehicle
LOG ?= $(DIST_DIR)/vehicle-report-c-demo.log

include ../../mk/c.mk
