REPO_ROOT ?= ../../..
SPEC := vehicle.lf
APP_NAME := vehicle-report-demo
BIN = $(DIST_DIR)/vehicle-report-demo
INPUT ?= ../../testdata/vehicle-report/valid/basic.vehicle
LOG ?= $(DIST_DIR)/vehicle-report-demo.log
RUN_ARGS = --input $(INPUT) --log $(LOG)

include ../../mk/go.mk
