REPO_ROOT ?= ../../..
SPEC := calc.lf
APP_NAME := calc-demo
BIN = $(DIST_DIR)/calc-demo
INPUT ?= ../../testdata/calc/valid/basic.calc
LOG ?= $(DIST_DIR)/calc-demo.log
RUN_ARGS = --input $(INPUT) --log $(LOG)

include ../../mk/go.mk
