REPO_ROOT ?= ../../..
SPEC := datakeeper.lf
BIN = $(DIST_DIR)/datakeeper-cpp-demo
INPUT ?= ../../testdata/datakeeper/valid/basic.dks
LOG ?= $(DIST_DIR)/datakeeper-cpp-demo.log

include ../../mk/cpp.mk
